# Generated by Django 3.2 on 2022-03-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rasm',
            field=models.ImageField(upload_to='rasmlar/'),
        ),
    ]
